// automatically generated by the FlatBuffers compiler, do not modify

package haruspex.producer.serialization.flatbuf;

public final class ContextType {
  private ContextType() { }
  public static final byte TRACE = 0;
  public static final byte ENTITY = 1;
  public static final byte BLOCK = 2;
  public static final byte POINT = 3;

  public static final String[] names = { "TRACE", "ENTITY", "BLOCK", "POINT", };

  public static String name(int e) { return names[e]; }
}

