/**
 * This package contains classes used by applications interested in browsing traces.
 * These are ImmutableTrace, ImmutableEntity, ImmutableBlock, ImmutablePoint. The package also contains 
 * the <code>Mutable</code> equivalent of those. A trace model can be created using mutable elements,
 *  for example from events generated by the {@link haruspex.producer producer API}, and transformed to 
 *  immutable.
 */
package haruspex.model;

